services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/dev.web.Dockerfile
    container_name: django
    volumes:
      - .:/usr/src/app/
      - staticfiles:/usr/src/app/public/staticfiles
      - media:/usr/src/app/public/media
    command: /usr/src/app/scripts/dev/dev.web.sh
    expose:
      - 8000
    env_file:
      - ./.env.dev.db
      - ./.env.dev
    depends_on:
      - database
      - mailhog

  database:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    env_file:
      - ./.env.dev.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  nginx:
    build:
      context: ./docker/dev/nginx
      dockerfile: dev.nginx.Dockerfile
    container_name: nginx
    volumes:
      - staticfiles:/usr/src/app/public/staticfiles
      - media:/usr/src/app/public/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  pgadmin4_data:
  staticfiles:
  media:
